version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka-1:
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://kafka-1:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_NUM_PARTITIONS: 3
      # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    healthcheck:
      test: nc -z kafka-1 19092 || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      # start_period: 30s
    depends_on:
      - zookeeper


  main-server:
    build:
      context: ./main-server
      dockerfile: Dockerfile
    volumes:
      - ./main-server/src:/app/src
    ports:
      - 3000:3000
    # env_file:
    #   - './.env'
  

  extractor-server:
    build:
      context: ./extractor
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      kafka-1:
        condition: service_healthy


  # mysql-database:
  #   image: mysql:8.0.33
  #   restart: always
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: '${MYSQL_DATABASE}'
  #     MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
  #   ports:
  #     - 3306:3306