version: '3.7'

services:
  main-server:
    build:
      context: ./main-server
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    # env_file:
    #   - './.env'
  
  extractor-server:
    build:
      context: ./extractor
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  # mysql-database:
  #   image: mysql:8.0.33
  #   restart: always
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: '${MYSQL_DATABASE}'
  #     MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
  #   ports:
  #     - 3306:3306